# Generated by Django 5.1.1 on 2024-09-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('info_text', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.CharField(max_length=1000)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.post')),
            ],
        ),
    ]
