# Generated by Django 5.1.1 on 2024-09-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='score',
            new_name='downvote',
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='info_text',
            field=models.CharField(max_length=500),
        ),
    ]
