# Generated by Django 5.1.1 on 2024-09-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_rename_downvote_post_downvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.IntegerField(default=16777215)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='location_lat',
            field=models.FloatField(default=36.1446206),
        ),
        migrations.AddField(
            model_name='post',
            name='location_long',
            field=models.FloatField(default=-86.8032659),
        ),
        migrations.AddField(
            model_name='post',
            name='location_street_address',
            field=models.CharField(default='1234 Abbey Road', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='deals.tag'),
        ),
    ]
